import { NextRequest, NextResponse } from 'next/server';

interface HealthData {
  checkIns: any[];
  vitals: any[];
  exercises: any[];
  nutrition: any[];
  water: any[];
  symptoms: any[];
  medications: any[];
  medicationDoses: any[];
  goals: any[];
}

export async function POST(request: NextRequest) {
  try {
    const { healthData, periodDays } = await request.json();
    
    // Process the health data into meaningful statistics
    const analysis = analyzeHealthData(healthData, periodDays);
    
    const apiKey = process.env.OPENROUTER_API_KEY;

    if (!apiKey) {
      // Return a comprehensive fallback report if no API key
      return NextResponse.json({
        report: generateComprehensiveReport(analysis, periodDays),
      });
    }

    const systemPrompt = `You are Faith, a clinical health analysis AI for AlagApp. Generate medically accurate health reports based on user data.

CRITICAL RULES:
- NO emojis whatsoever
- NO markdown formatting (no asterisks, no bold, no italics)
- Use professional, clinical language
- Be precise with numbers and statistics
- Provide evidence-based recommendations
- Reference specific data points from the user's records
- Use proper medical terminology where appropriate
- Always include disclaimer about consulting healthcare professionals
- Format using plain text with clear section headers using === or ---
- Use numbered lists (1. 2. 3.) for recommendations
- Use bullet points with dashes (-) for lists, not asterisks
- Keep tone supportive but professional`;

    const userPrompt = `Generate a ${getPeriodLabel(periodDays)} Health Report based on this analyzed health data:

DATE RANGE: ${analysis.dateRange.start} to ${analysis.dateRange.end}

CHECK-INS (${analysis.checkIns.count} entries):
- Average Mood: ${analysis.checkIns.avgMood}/5
- Average Energy: ${analysis.checkIns.avgEnergy}/5
- Mood Trend: ${analysis.checkIns.moodTrend}
- Common notes: ${analysis.checkIns.commonNotes.join(', ') || 'None recorded'}

VITALS (${analysis.vitals.count} readings):
${analysis.vitals.bloodPressure.count > 0 ? `- Blood Pressure: Avg ${analysis.vitals.bloodPressure.avgSystolic}/${analysis.vitals.bloodPressure.avgDiastolic} mmHg (${analysis.vitals.bloodPressure.count} readings)` : '- Blood Pressure: No readings'}
${analysis.vitals.heartRate.count > 0 ? `- Heart Rate: Avg ${analysis.vitals.heartRate.avg} bpm, Range ${analysis.vitals.heartRate.min}-${analysis.vitals.heartRate.max} bpm` : '- Heart Rate: No readings'}
${analysis.vitals.weight.count > 0 ? `- Weight: ${analysis.vitals.weight.latest} kg (${Number(analysis.vitals.weight.change) > 0 ? '+' : ''}${analysis.vitals.weight.change} kg change)` : '- Weight: No readings'}
${analysis.vitals.sleep.count > 0 ? `- Sleep: Avg ${analysis.vitals.sleep.avg} hours/night` : '- Sleep: No readings'}
${analysis.vitals.glucose.count > 0 ? `- Blood Glucose: Avg ${analysis.vitals.glucose.avg} mg/dL` : '- Blood Glucose: No readings'}
${analysis.vitals.oxygen.count > 0 ? `- Oxygen Saturation: Avg ${analysis.vitals.oxygen.avg}%` : '- Oxygen Saturation: No readings'}

EXERCISE (${analysis.exercise.count} sessions):
- Total Duration: ${analysis.exercise.totalMinutes} minutes
- Total Calories Burned: ${analysis.exercise.totalCalories} kcal
- Most Common Activity: ${analysis.exercise.mostCommon || 'None'}
- Average Session: ${analysis.exercise.avgDuration} minutes

NUTRITION (${analysis.nutrition.count} meals logged):
- Average Daily Calories: ${analysis.nutrition.avgDailyCalories} kcal
- Average Protein: ${analysis.nutrition.avgProtein}g/day
- Average Carbs: ${analysis.nutrition.avgCarbs}g/day
- Average Fat: ${analysis.nutrition.avgFat}g/day

HYDRATION (${analysis.hydration.count} logs):
- Average Daily Intake: ${analysis.hydration.avgDaily} ml
- Days Goal Met (2000ml): ${analysis.hydration.daysGoalMet}/${periodDays}

SYMPTOMS (${analysis.symptoms.count} logged):
- Most Common: ${analysis.symptoms.mostCommon.join(', ') || 'None'}
- Average Severity: ${analysis.symptoms.avgSeverity}/10
- Ongoing Symptoms: ${analysis.symptoms.ongoing.join(', ') || 'None'}

MEDICATIONS (${analysis.medications.active} active):
- Names: ${analysis.medications.names.join(', ') || 'None'}
- Adherence Rate: ${analysis.medications.adherenceRate}%

ACTIVE GOALS: ${analysis.goals.count}
${analysis.goals.list.map((g: string) => `- ${g}`).join('\n') || '- No active goals'}

Generate a comprehensive health report with these exact sections:
1. REPORT HEADER - Title, date range, generated by Faith AI
2. EXECUTIVE SUMMARY - 2-3 sentence overview
3. KEY METRICS - Important numbers at a glance
4. POSITIVE OBSERVATIONS - What's going well (be specific with data)
5. AREAS REQUIRING ATTENTION - Concerns based on data (be clinical but supportive)
6. CLINICAL RECOMMENDATIONS - 3-5 specific, actionable, evidence-based suggestions
7. DISCLAIMER - Standard medical disclaimer

FORMATTING RULES:
- Use === for major section dividers
- Use --- for subsections
- Use numbered lists (1. 2. 3.) for recommendations
- Use dashes (-) for bullet points, NOT asterisks
- NO bold text (no ** symbols)
- NO italic text (no * symbols)
- NO markdown formatting of any kind
- Be specific with numbers. Reference actual data points.
- Keep total response under 600 words.
- NO EMOJIS.`;

    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': process.env.NEXT_PUBLIC_APP_URL || 'https://alagapp.vercel.app',
        'X-Title': 'AlagApp Health Assistant',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.0-flash-001',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
        max_tokens: 1500,
        temperature: 0.3, // Lower temperature for more consistent, clinical output
      }),
    });

    if (!response.ok) {
      console.error('OpenRouter API error:', await response.text());
      return NextResponse.json({
        report: generateComprehensiveReport(analysis, periodDays),
      });
    }

    const data = await response.json();
    const report = data.choices?.[0]?.message?.content || generateComprehensiveReport(analysis, periodDays);

    return NextResponse.json({ report });
  } catch (error) {
    console.error('AI Report error:', error);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}

function getPeriodLabel(days: number): string {
  if (days <= 7) return 'Weekly';
  if (days <= 14) return 'Bi-Weekly';
  return 'Monthly';
}

function analyzeHealthData(data: HealthData, days: number) {
  const endDate = new Date();
  const startDate = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  
  // Check-ins analysis
  const checkIns = data.checkIns || [];
  const avgMood = checkIns.length > 0 
    ? (checkIns.reduce((sum, c) => sum + (c.mood || c.mood_score || 0), 0) / checkIns.length).toFixed(1)
    : '0.0';
  const avgEnergy = checkIns.length > 0
    ? (checkIns.reduce((sum, c) => sum + (c.energy || c.energy_level || 0), 0) / checkIns.length).toFixed(1)
    : '0.0';
  
  // Determine mood trend
  let moodTrend = 'Stable';
  if (checkIns.length >= 3) {
    const recentMoods = checkIns.slice(0, Math.min(3, checkIns.length)).map(c => c.mood || c.mood_score || 0);
    const olderMoods = checkIns.slice(-Math.min(3, checkIns.length)).map(c => c.mood || c.mood_score || 0);
    const recentAvg = recentMoods.reduce((a, b) => a + b, 0) / recentMoods.length;
    const olderAvg = olderMoods.reduce((a, b) => a + b, 0) / olderMoods.length;
    if (recentAvg > olderAvg + 0.5) moodTrend = 'Improving';
    else if (recentAvg < olderAvg - 0.5) moodTrend = 'Declining';
  }

  // Vitals analysis
  const vitals = data.vitals || [];
  const bpReadings = vitals.filter(v => v.type === 'blood_pressure');
  const hrReadings = vitals.filter(v => v.type === 'heart_rate');
  const weightReadings = vitals.filter(v => v.type === 'weight');
  const sleepReadings = vitals.filter(v => v.type === 'sleep');
  const glucoseReadings = vitals.filter(v => v.type === 'glucose');
  const oxygenReadings = vitals.filter(v => v.type === 'oxygen');

  // Exercise analysis
  const exercises = data.exercises || [];
  const totalMinutes = exercises.reduce((sum, e) => sum + (e.duration_minutes || 0), 0);
  const totalCalories = exercises.reduce((sum, e) => sum + (e.calories_burned || 0), 0);
  const activityCounts: Record<string, number> = {};
  exercises.forEach(e => {
    const type = e.activity_type || 'Unknown';
    activityCounts[type] = (activityCounts[type] || 0) + 1;
  });
  const mostCommonActivity = Object.entries(activityCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || 'None';

  // Nutrition analysis
  const nutrition = data.nutrition || [];
  const dailyNutrition: Record<string, { calories: number; protein: number; carbs: number; fat: number }> = {};
  nutrition.forEach(n => {
    const date = new Date(n.logged_at).toDateString();
    if (!dailyNutrition[date]) {
      dailyNutrition[date] = { calories: 0, protein: 0, carbs: 0, fat: 0 };
    }
    dailyNutrition[date].calories += n.calories || 0;
    dailyNutrition[date].protein += n.protein_g || 0;
    dailyNutrition[date].carbs += n.carbs_g || 0;
    dailyNutrition[date].fat += n.fat_g || 0;
  });
  const nutritionDays = Object.keys(dailyNutrition).length || 1;
  const totalNutrition = Object.values(dailyNutrition).reduce(
    (acc, day) => ({
      calories: acc.calories + day.calories,
      protein: acc.protein + day.protein,
      carbs: acc.carbs + day.carbs,
      fat: acc.fat + day.fat,
    }),
    { calories: 0, protein: 0, carbs: 0, fat: 0 }
  );

  // Hydration analysis
  const water = data.water || [];
  const dailyWater: Record<string, number> = {};
  water.forEach(w => {
    const date = new Date(w.logged_at).toDateString();
    dailyWater[date] = (dailyWater[date] || 0) + (w.amount_ml || 0);
  });
  const waterDays = Object.keys(dailyWater).length || 1;
  const totalWater = Object.values(dailyWater).reduce((a, b) => a + b, 0);
  const daysGoalMet = Object.values(dailyWater).filter(ml => ml >= 2000).length;

  // Symptoms analysis
  const symptoms = data.symptoms || [];
  const symptomCounts: Record<string, number> = {};
  symptoms.forEach(s => {
    const name = s.symptom || 'Unknown';
    symptomCounts[name] = (symptomCounts[name] || 0) + 1;
  });
  const mostCommonSymptoms = Object.entries(symptomCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([name]) => name);
  const avgSeverity = symptoms.length > 0
    ? (symptoms.reduce((sum, s) => sum + (s.severity || 0), 0) / symptoms.length).toFixed(1)
    : '0.0';
  const ongoingSymptoms = symptoms.filter(s => s.is_ongoing).map(s => s.symptom);

  // Medications analysis
  const medications = data.medications || [];
  const medicationDoses = data.medicationDoses || [];
  const takenDoses = medicationDoses.filter(d => d.status === 'taken').length;
  const totalDoses = medicationDoses.length || 1;
  const adherenceRate = Math.round((takenDoses / totalDoses) * 100);

  // Goals
  const goals = data.goals || [];

  return {
    dateRange: {
      start: startDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
      end: endDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    },
    checkIns: {
      count: checkIns.length,
      avgMood,
      avgEnergy,
      moodTrend,
      commonNotes: checkIns.slice(0, 3).map(c => c.notes).filter(Boolean),
    },
    vitals: {
      count: vitals.length,
      bloodPressure: {
        count: bpReadings.length,
        avgSystolic: bpReadings.length > 0 ? Math.round(bpReadings.reduce((s, v) => s + v.value, 0) / bpReadings.length) : 0,
        avgDiastolic: bpReadings.length > 0 ? Math.round(bpReadings.reduce((s, v) => s + (v.value_secondary || 0), 0) / bpReadings.length) : 0,
      },
      heartRate: {
        count: hrReadings.length,
        avg: hrReadings.length > 0 ? Math.round(hrReadings.reduce((s, v) => s + v.value, 0) / hrReadings.length) : 0,
        min: hrReadings.length > 0 ? Math.min(...hrReadings.map(v => v.value)) : 0,
        max: hrReadings.length > 0 ? Math.max(...hrReadings.map(v => v.value)) : 0,
      },
      weight: {
        count: weightReadings.length,
        latest: weightReadings.length > 0 ? weightReadings[0].value : 0,
        change: weightReadings.length >= 2 ? (weightReadings[0].value - weightReadings[weightReadings.length - 1].value).toFixed(1) : 0,
      },
      sleep: {
        count: sleepReadings.length,
        avg: sleepReadings.length > 0 ? (sleepReadings.reduce((s, v) => s + v.value, 0) / sleepReadings.length).toFixed(1) : 0,
      },
      glucose: {
        count: glucoseReadings.length,
        avg: glucoseReadings.length > 0 ? Math.round(glucoseReadings.reduce((s, v) => s + v.value, 0) / glucoseReadings.length) : 0,
      },
      oxygen: {
        count: oxygenReadings.length,
        avg: oxygenReadings.length > 0 ? Math.round(oxygenReadings.reduce((s, v) => s + v.value, 0) / oxygenReadings.length) : 0,
      },
    },
    exercise: {
      count: exercises.length,
      totalMinutes,
      totalCalories,
      avgDuration: exercises.length > 0 ? Math.round(totalMinutes / exercises.length) : 0,
      mostCommon: mostCommonActivity,
    },
    nutrition: {
      count: nutrition.length,
      avgDailyCalories: Math.round(totalNutrition.calories / nutritionDays),
      avgProtein: Math.round(totalNutrition.protein / nutritionDays),
      avgCarbs: Math.round(totalNutrition.carbs / nutritionDays),
      avgFat: Math.round(totalNutrition.fat / nutritionDays),
    },
    hydration: {
      count: water.length,
      avgDaily: Math.round(totalWater / waterDays),
      daysGoalMet,
    },
    symptoms: {
      count: symptoms.length,
      mostCommon: mostCommonSymptoms,
      avgSeverity,
      ongoing: Array.from(new Set(ongoingSymptoms)),
    },
    medications: {
      active: medications.length,
      names: medications.map(m => m.name),
      adherenceRate: medicationDoses.length > 0 ? adherenceRate : 100,
    },
    goals: {
      count: goals.length,
      list: goals.map(g => g.title || g.goal_type),
    },
  };
}

function generateComprehensiveReport(analysis: any, days: number): string {
  const periodLabel = getPeriodLabel(days);
  
  // Build positive observations
  const positives: string[] = [];
  if (parseFloat(analysis.checkIns.avgMood) >= 3.5) {
    positives.push(`Mood scores averaging ${analysis.checkIns.avgMood}/5 indicate generally positive mental wellbeing`);
  }
  if (analysis.checkIns.moodTrend === 'Improving') {
    positives.push('Mood trend shows improvement over the reporting period');
  }
  if (analysis.exercise.count >= 3) {
    positives.push(`${analysis.exercise.count} exercise sessions logged, totaling ${analysis.exercise.totalMinutes} minutes of physical activity`);
  }
  if (analysis.hydration.daysGoalMet >= days * 0.5) {
    positives.push(`Hydration goal met on ${analysis.hydration.daysGoalMet} out of ${days} days`);
  }
  if (analysis.medications.adherenceRate >= 80) {
    positives.push(`Medication adherence rate of ${analysis.medications.adherenceRate}% demonstrates good compliance`);
  }
  if (analysis.vitals.bloodPressure.count > 0 && analysis.vitals.bloodPressure.avgSystolic < 130) {
    positives.push(`Average blood pressure ${analysis.vitals.bloodPressure.avgSystolic}/${analysis.vitals.bloodPressure.avgDiastolic} mmHg within normal range`);
  }
  if (positives.length === 0) {
    positives.push('You are actively tracking your health data, which is an important first step');
  }

  // Build areas of concern
  const concerns: string[] = [];
  if (analysis.checkIns.count < days * 0.5) {
    concerns.push(`Check-in frequency (${analysis.checkIns.count}/${days} days) below recommended daily tracking`);
  }
  if (parseFloat(analysis.checkIns.avgMood) < 3 && analysis.checkIns.count > 0) {
    concerns.push(`Average mood score of ${analysis.checkIns.avgMood}/5 suggests attention to mental wellbeing may be beneficial`);
  }
  if (analysis.exercise.count < 3) {
    concerns.push(`Exercise frequency (${analysis.exercise.count} sessions) below recommended 3-5 sessions per week`);
  }
  if (analysis.hydration.avgDaily < 1500 && analysis.hydration.count > 0) {
    concerns.push(`Average daily water intake of ${analysis.hydration.avgDaily}ml below recommended 2000ml minimum`);
  }
  if (analysis.vitals.sleep.count > 0 && parseFloat(analysis.vitals.sleep.avg) < 7) {
    concerns.push(`Average sleep duration of ${analysis.vitals.sleep.avg} hours below recommended 7-9 hours`);
  }
  if (analysis.symptoms.ongoing.length > 0) {
    concerns.push(`Ongoing symptoms reported: ${analysis.symptoms.ongoing.join(', ')}`);
  }
  if (analysis.medications.adherenceRate < 80 && analysis.medications.active > 0) {
    concerns.push(`Medication adherence at ${analysis.medications.adherenceRate}% - consistency is important for effectiveness`);
  }

  // Build recommendations
  const recommendations: string[] = [];
  if (analysis.checkIns.count < days) {
    recommendations.push('Complete daily check-ins to establish baseline mood and energy patterns');
  }
  if (analysis.exercise.count < 3) {
    recommendations.push('Aim for at least 150 minutes of moderate-intensity exercise per week (WHO guidelines)');
  }
  if (analysis.hydration.avgDaily < 2000) {
    recommendations.push('Increase water intake to minimum 2000ml daily; consider setting hourly reminders');
  }
  if (analysis.vitals.count < 3) {
    recommendations.push('Log vital signs regularly for better health trend analysis');
  }
  if (analysis.nutrition.count < days * 2) {
    recommendations.push('Track meals more consistently for accurate nutritional insights');
  }
  if (recommendations.length === 0) {
    recommendations.push('Continue current health tracking habits');
    recommendations.push('Consider setting specific, measurable health goals');
  }

  return `${periodLabel.toUpperCase()} HEALTH REPORT
${analysis.dateRange.start} - ${analysis.dateRange.end}
Generated by Faith AI

============================================================

EXECUTIVE SUMMARY
-----------------
This report analyzes ${analysis.checkIns.count} check-ins, ${analysis.vitals.count} vital readings, ${analysis.exercise.count} exercise sessions, and ${analysis.nutrition.count} meal logs over the past ${days} days. ${analysis.checkIns.count > 0 ? `Average mood was ${analysis.checkIns.avgMood}/5 with energy levels at ${analysis.checkIns.avgEnergy}/5.` : 'Limited mood data available for analysis.'}

============================================================

KEY METRICS
-----------
Check-ins: ${analysis.checkIns.count} entries (${Math.round(analysis.checkIns.count / days * 100)}% consistency)
Mood: ${analysis.checkIns.avgMood}/5 average | Energy: ${analysis.checkIns.avgEnergy}/5 average
Exercise: ${analysis.exercise.totalMinutes} minutes total | ${analysis.exercise.totalCalories} kcal burned
Nutrition: ${analysis.nutrition.avgDailyCalories} kcal/day average
Hydration: ${analysis.hydration.avgDaily} ml/day average
Symptoms: ${analysis.symptoms.count} logged | Avg severity: ${analysis.symptoms.avgSeverity}/10
Medications: ${analysis.medications.active} active | ${analysis.medications.adherenceRate}% adherence

============================================================

POSITIVE OBSERVATIONS
---------------------
${positives.map(p => `* ${p}`).join('\n')}

============================================================

AREAS REQUIRING ATTENTION
-------------------------
${concerns.length > 0 ? concerns.map(c => `* ${c}`).join('\n') : '* No significant concerns identified based on available data'}

============================================================

CLINICAL RECOMMENDATIONS
------------------------
${recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

============================================================

DISCLAIMER
----------
This report is generated for informational and educational purposes only. It does not constitute medical advice, diagnosis, or treatment. Always consult with qualified healthcare professionals regarding any health concerns or before making changes to medication, diet, or exercise routines. If you experience severe symptoms or a medical emergency, seek immediate medical attention.

============================================================
Report generated by Faith AI - AlagApp Health Assistant`;
}